import Foundation

extension Definition {

  public enum `PriceCurrencyCode`: String, Encodable, Sendable {
    case `adp`
    case `aed`
    case `afa`
    case `afn`
    case `alk`
    case `all`
    case `amd`
    case `ang`
    case `aoa`
    case `aok`
    case `aon`
    case `aor`
    case `ara`
    case `arp`
    case `ars`
    case `ary`
    case `ats`
    case `aud`
    case `awg`
    case `aym`
    case `azm`
    case `azn`
    case `bad`
    case `bam`
    case `bbd`
    case `bdt`
    case `bec`
    case `bef`
    case `bel`
    case `bgj`
    case `bgk`
    case `bgl`
    case `bgn`
    case `bhd`
    case `bif`
    case `bmd`
    case `bnd`
    case `bob`
    case `bop`
    case `bov`
    case `brb`
    case `brc`
    case `bre`
    case `brl`
    case `brn`
    case `brr`
    case `bsd`
    case `btn`
    case `buk`
    case `bwp`
    case `byb`
    case `byn`
    case `byr`
    case `bzd`
    case `cad`
    case `cdf`
    case `chc`
    case `che`
    case `chf`
    case `chw`
    case `clf`
    case `clp`
    case `cny`
    case `cop`
    case `cou`
    case `crc`
    case `csd`
    case `csj`
    case `csk`
    case `cuc`
    case `cup`
    case `cve`
    case `cyp`
    case `czk`
    case `ddm`
    case `dem`
    case `djf`
    case `dkk`
    case `dop`
    case `dzd`
    case `ecs`
    case `ecv`
    case `eek`
    case `egp`
    case `ern`
    case `esa`
    case `esb`
    case `esp`
    case `etb`
    case `eur`
    case `fim`
    case `fjd`
    case `fkp`
    case `frf`
    case `gbp`
    case `gek`
    case `gel`
    case `ghc`
    case `ghp`
    case `ghs`
    case `gip`
    case `gmd`
    case `gne`
    case `gnf`
    case `gns`
    case `gqe`
    case `grd`
    case `gtq`
    case `gwe`
    case `gwp`
    case `gyd`
    case `hkd`
    case `hnl`
    case `hrd`
    case `hrk`
    case `htg`
    case `huf`
    case `idr`
    case `iep`
    case `ilp`
    case `ilr`
    case `ils`
    case `inr`
    case `iqd`
    case `irr`
    case `isj`
    case `isk`
    case `itl`
    case `jmd`
    case `jod`
    case `jpy`
    case `kes`
    case `kgs`
    case `khr`
    case `kmf`
    case `kpw`
    case `krw`
    case `kwd`
    case `kyd`
    case `kzt`
    case `laj`
    case `lak`
    case `lbp`
    case `lkr`
    case `lrd`
    case `lsl`
    case `lsm`
    case `ltl`
    case `ltt`
    case `luc`
    case `luf`
    case `lul`
    case `lvl`
    case `lvr`
    case `lyd`
    case `mad`
    case `mdl`
    case `mga`
    case `mgf`
    case `mkd`
    case `mlf`
    case `mmk`
    case `mnt`
    case `mop`
    case `mro`
    case `mru`
    case `mtl`
    case `mtp`
    case `mur`
    case `mvq`
    case `mvr`
    case `mwk`
    case `mxn`
    case `mxp`
    case `mxv`
    case `myr`
    case `mze`
    case `mzm`
    case `mzn`
    case `nad`
    case `ngn`
    case `nic`
    case `nio`
    case `nlg`
    case `nok`
    case `npr`
    case `nzd`
    case `omr`
    case `pab`
    case `peh`
    case `pei`
    case `pen`
    case `pes`
    case `pgk`
    case `php`
    case `pkr`
    case `pln`
    case `plz`
    case `pte`
    case `pyg`
    case `qar`
    case `rhd`
    case `rok`
    case `rol`
    case `ron`
    case `rsd`
    case `rub`
    case `rur`
    case `rwf`
    case `sar`
    case `sbd`
    case `scr`
    case `sdd`
    case `sdg`
    case `sdp`
    case `sek`
    case `sgd`
    case `sit`
    case `skk`
    case `sll`
    case `sos`
    case `srd`
    case `srg`
    case `ssp`
    case `std`
    case `stn`
    case `sur`
    case `svc`
    case `syp`
    case `szl`
    case `thb`
    case `tjr`
    case `tjs`
    case `tmm`
    case `tmt`
    case `tnd`
    case `top`
    case `tpe`
    case `trl`
    case `try`
    case `ttd`
    case `twd`
    case `uah`
    case `uak`
    case `ugs`
    case `ugw`
    case `ugx`
    case `usd`
    case `usn`
    case `uss`
    case `uyi`
    case `uyn`
    case `uyp`
    case `uyu`
    case `uyw`
    case `uzs`
    case `veb`
    case `vef`
    case `ves`
    case `vnc`
    case `vnd`
    case `vuv`
    case `wst`
    case `xaf`
    case `xag`
    case `xau`
    case `xba`
    case `xbb`
    case `xbc`
    case `xbd`
    case `xcd`
    case `xdr`
    case `xeu`
    case `xfo`
    case `xfu`
    case `xof`
    case `xpd`
    case `xpf`
    case `xpt`
    case `xre`
    case `xsu`
    case `xts`
    case `xua`
    case `xxx`
    case `yer`
    case `yud`
    case `yum`
    case `yun`
    case `zal`
    case `zar`
    case `zmk`
    case `zmw`
    case `zrn`
    case `zrz`
    case `zwc`
    case `zwd`
    case `zwl`
    case `zwn`
    case `zwr`
  }
}
