import Foundation

extension Definition {

  public enum `Button`: String, Encodable, Sendable {
    case `addId` = "add_id"
    case `addLogin` = "add_login"
    case `addNow` = "add_now"
    case `addPaymentInfo` = "add_payment_info"
    case `addSecret` = "add_secret"
    case `addSecureNote` = "add_secure_note"
    case `askLater` = "ask_later"
    case `back`
    case `bookCall` = "book_call"
    case `buyDashlane` = "buy_dashlane"
    case `buySeats` = "buy_seats"
    case `cancel`
    case `cancelSubscription` = "cancel_subscription"
    case `changeUserLoginEmail` = "change_user_login_email"
    case `changeUserRole` = "change_user_role"
    case `checkHelpCenterForExtraGuidance` = "check_help_center_for_extra_guidance"
    case `checkImproveHealthScore` = "check_improve_health_score"
    case `checkOtherRiskyPasswords` = "check_other_risky_passwords"
    case `checkSupportedDevices` = "check_supported_devices"
    case `close`
    case `confirmAndPay` = "confirm_and_pay"
    case `confirmCancellation` = "confirm_cancellation"
    case `confirmUpgrade` = "confirm_upgrade"
    case `contactSales` = "contact_sales"
    case `contactSupportTeam` = "contact_support_team"
    case `copyReferralLink` = "copy_referral_link"
    case `createPersonalAccount` = "create_personal_account"
    case `discard`
    case `dismiss`
    case `done`
    case `downloadBillingHistory` = "download_billing_history"
    case `downloadCsv` = "download_csv"
    case `downloadExtension` = "download_extension"
    case `downloadKey` = "download_key"
    case `extendTrial` = "extend_trial"
    case `goToLogins` = "go_to_logins"
    case `importLogins` = "import_logins"
    case `importSecrets` = "import_secrets"
    case `importSecureNotes` = "import_secure_notes"
    case `inviteMembers` = "invite_members"
    case `inviteNow` = "invite_now"
    case `inviteReferralsByEmail` = "invite_referrals_by_email"
    case `inviteUsers` = "invite_users"
    case `learnMoreAboutNudges` = "learn_more_about_nudges"
    case `learnMoreAboutOurRefundPolicy` = "learn_more_about_our_refund_policy"
    case `learnMoreAboutPhishingProtection` = "learn_more_about_phishing_protection"
    case `manageLogins` = "manage_logins"
    case `manageUserGroupAccess` = "manage_user_group_access"
    case `next`
    case `notifyMe` = "notify_me"
    case `ok`
    case `open`
    case `openAdminConsole` = "open_admin_console"
    case `openDashboard` = "open_dashboard"
    case `openGroupsPage` = "open_groups_page"
    case `openPasswordHealthScore` = "open_password_health_score"
    case `openSharingCenter` = "open_sharing_center"
    case `openUsersPage` = "open_users_page"
    case `openVault` = "open_vault"
    case `reInviteUsers` = "re_invite_users"
    case `reactivateSubscription` = "reactivate_subscription"
    case `redeemOffer` = "redeem_offer"
    case `referABusiness` = "refer_a_business"
    case `referAFriend` = "refer_a_friend"
    case `remainFree` = "remain_free"
    case `removeUserFromTeam` = "remove_user_from_team"
    case `requestPurchaseOrder` = "request_purchase_order"
    case `requestRefund` = "request_refund"
    case `restartPremiumSubscription` = "restart_premium_subscription"
    case `resume`
    case `reviewSubscription` = "review_subscription"
    case `revokeKey` = "revoke_key"
    case `searchBar` = "search_bar"
    case `seeAll` = "see_all"
    case `seeB2BPlanTiers` = "see_b2b_plan_tiers"
    case `seeNudgesSetupGuide` = "see_nudges_setup_guide"
    case `seeOtherMethods` = "see_other_methods"
    case `seePlan` = "see_plan"
    case `seeSetupGuide` = "see_setup_guide"
    case `seeUsers` = "see_users"
    case `selectBusinessPlan` = "select_business_plan"
    case `selectStandardPlan` = "select_standard_plan"
    case `selectStarterPlan` = "select_starter_plan"
    case `selectTeamPlan` = "select_team_plan"
    case `setUp` = "set_up"
    case `shareReferralLinkOnX` = "share_referral_link_on_x"
    case `skip`
    case `start`
    case `startSharing` = "start_sharing"
    case `submit`
    case `submitAntiPhishingFeedback` = "submit_anti_phishing_feedback"
    case `submitNudgesFeedback` = "submit_nudges_feedback"
    case `tryNow` = "try_now"
    case `unfreezeAccount` = "unfreeze_account"
    case `updatePaymentMethod` = "update_payment_method"
    case `upgradeBusinessPlusTier` = "upgrade_business_plus_tier"
    case `upgradeBusinessTier` = "upgrade_business_tier"
    case `upgradeFriendsAndFamilyPlan` = "upgrade_friends_and_family_plan"
    case `upgradePaidPlan` = "upgrade_paid_plan"
    case `upgradePremiumPlan` = "upgrade_premium_plan"
    case `viewAllPlans` = "view_all_plans"
    case `viewUserLogins` = "view_user_logins"
  }
}
