import DesignSystem
import SwiftUI

struct TokenHelpView: View {

  let title: String
  let message: String
  let cta: String

  let completion: () -> Void

  var body: some View {
    mainView
      .overlay(overlayButton)
  }

  var mainView: some View {
    ScrollView {
      VStack(spacing: 60) {
        Spacer()
        Image(asset: AuthenticatorAsset.tokenHelp)
        VStack(spacing: 16) {
          Text(title)
            .font(.authenticator(.mediumTitle))
            .multilineTextAlignment(.center)
            .foregroundColor(.ds.text.neutral.catchy)
            .fixedSize(horizontal: false, vertical: true)
          Text(message)
            .multilineTextAlignment(.center)
            .font(.body)
            .foregroundColor(.ds.text.neutral.standard)
            .fixedSize(horizontal: false, vertical: true)
        }
      }.padding(.bottom, 50)
        .padding(.horizontal, 24)
    }.backgroundColorIgnoringSafeArea(.ds.background.alternate)
      .navigationBarBackButtonHidden(true)
  }

  var overlayButton: some View {
    VStack {
      Spacer()
      Button(cta, action: completion)
        .buttonStyle(.designSystem(.titleOnly))
    }
    .padding(.horizontal, 24)
    .padding(.bottom, 24)
  }
}

struct TokenHelpView_previews: PreviewProvider {
  static var previews: some View {
    TokenHelpView(
      title: "Use 2FA tokens to securely log in to your accounts",
      message:
        "Log in to your accounts securely with your password and a 6-digit token generated by Dashlane Authenticator.",
      cta: L10n.Localizable.addOtpFlowAddNewCta
    ) {}
  }
}
