public enum VaultItemEnumeration {
  case credential(Credential)
  case secureNote(SecureNote)
  case secret(Secret)
  case bankAccount(BankAccount)
  case creditCard(CreditCard)
  case identity(Identity)
  case email(Email)
  case phone(Phone)
  case address(Address)
  case company(Company)
  case personalWebsite(PersonalWebsite)
  case passport(Passport)
  case idCard(IDCard)
  case fiscalInformation(FiscalInformation)
  case socialSecurityInformation(SocialSecurityInformation)
  case drivingLicence(DrivingLicence)
  case passkey(Passkey)
  case wifi(WiFi)
}
