public enum Page: String, Encodable, Sendable {
  case `importCsvSelectSpace` = "import/csv/select_space"
  case `tacAccountBuy` = "tac/account/buy"
  case `itemFiscalStatement` = "item/fiscal_statement"
  case `itemPaypal` = "item/paypal"
  case `settingsAccount` = "settings/account"
  case `importBackupfile` = "import/backupfile"
  case `itemPaypalCreate` = "item/paypal/create"
  case `onboarding`
  case `toolsPasswordChangerErrorLoginFailure` = "tools/password_changer/error/login_failure"
  case `importBackupfileEnterPassword` = "import/backupfile/enter_password"
  case `autofillDropdownAddBankStatement` = "autofill/dropdown/add_bank_statement"
  case `itemPasskeyList` = "item/passkey/list"
  case `authenticatorAppHome` = "authenticator_app/home"
  case `tacSettings` = "tac/settings"
  case `toolsPasswordChangerError` = "tools/password_changer/error"
  case `loginDeviceTransferRequestRejected` = "login/device_transfer/request_rejected"
  case `sharingGroupMember` = "sharing/group/member"
  case `autofillKeyboard` = "autofill/keyboard"
  case `settingsMoreFeatures` = "settings/more_features"
  case `paywallPasswordChanger` = "paywall/password_changer"
  case `settingsSecurityProtectWithMasterPasswordIds` =
    "settings/security/protect_with_master_password_ids"
  case `itemWebsiteDetails` = "item/website/details"
  case `navigationRevampAnnouncementNewBottomActions` =
    "navigation_revamp_announcement/new_bottom_actions"
  case `settingsAddNewDevice` = "settings/add_new_device"
  case `settingsSecurityTwoFactorAuthenticationEnable6DigitsCode` =
    "settings/security/two_factor_authentication/enable/6_digits_code"
  case `review`
  case `homeOnboardingChecklistModalDisplay` = "home/onboarding_checklist_modal_display"
  case `itemCompany` = "item/company"
  case `help`
  case `itemSocialSecurityStatement` = "item/social_security_statement"
  case `settingsSecurityTwoFactorAuthenticationEnableSecurityLevel` =
    "settings/security/two_factor_authentication/enable/security_level"
  case `tacModalReasonsToCancelSubscription` = "tac/modal_reasons_to_cancel_subscription"
  case `plansManagementRefundDone` = "plans_management/refund_done"
  case `loginEnforce2FaBusiness` = "login/enforce_2fa_business"
  case `notificationSecurityList` = "notification/security/list"
  case `importCsvSuccess` = "import/csv/success"
  case `accountCreationInstallExtension` = "account_creation/install_extension"
  case `toolsDarkWebMonitoringAlert` = "tools/dark_web_monitoring/alert"
  case `antiphishingRedirect` = "antiphishing_redirect"
  case `homeOnboardingChecklistAddFirstLoginWebsiteList` =
    "home/onboarding_checklist/add_first_login/website_list"
  case `importSessionTimeout` = "import/session_timeout"
  case `itemBankStatementDetails` = "item/bank_statement/details"
  case `accountCreationTermsServices` = "account_creation/terms_services"
  case `accountCreationConfirmMasterPassword` = "account_creation/confirm_master_password"
  case `toolsAuthenticatorSetupQrCode` = "tools/authenticator/setup/qr_code"
  case `settingsSecurityTwoFactorAuthenticationDisable` =
    "settings/security/two_factor_authentication/disable"
  case `settingsExport` = "settings/export"
  case `introductoryOffers` = "introductory_offers"
  case `authenticatorAppAddAccountTokenHowToLogInAccount` =
    "authenticator_app/add_account_token/how_to_log_in_account"
  case `itemSecretList` = "item/secret/list"
  case `tacSso` = "tac/sso"
  case `dropdown`
  case `autofillNotificationAutologin` = "autofill/notification/autologin"
  case `sharingGroupMemberList` = "sharing/group/member/list"
  case `collectionQuickActionsDropdown` = "collection/quick_actions_dropdown"
  case `importCsvPreviewDataUpload` = "import/csv/preview_data_upload"
  case `homeAddItem` = "home/add_item"
  case `tac`
  case `tacGroupDetails` = "tac/group/details"
  case `itemQuickActionsDropdown` = "item/quick_actions_dropdown"
  case `importComputer` = "import/computer"
  case `settingsMore` = "settings/more"
  case `tacAccountSendFeedback` = "tac/account/send_feedback"
  case `settingsSecurityProtectWithMasterPassword` =
    "settings/security/protect_with_master_password"
  case `autofillNotificationWarningGeneratePasswordDashlaneAccountEmail` =
    "autofill/notification/warning/generate_password_dashlane_account_email"
  case `settingsSecurityProtectWithMasterPasswordPaymentsDisable` =
    "settings/security/protect_with_master_password_payments/disable"
  case `settingsSecurityTwoFactorAuthentication` = "settings/security/two_factor_authentication"
  case `passwordHistoryUnsaved` = "password_history/unsaved"
  case `tacOrderConfirmation` = "tac/order_confirmation"
  case `tacActivity` = "tac/activity"
  case `autofillDropdownAddPaypal` = "autofill/dropdown/add_paypal"
  case `collectionDelete` = "collection/delete"
  case `autofillNotificationAuthenticate` = "autofill/notification/authenticate"
  case `plansManagementRefundError` = "plans_management/refund_error"
  case `notificationOnboardingPinExtension` = "notification/onboarding/pin_extension"
  case `itemEmailDetails` = "item/email/details"
  case `autofillDropdownAddWebsite` = "autofill/dropdown/add_website"
  case `settingsSecurityTwoFactorAuthenticationEnableDownloadAuthenticator` =
    "settings/security/two_factor_authentication/enable/download_authenticator"
  case `settingsAddNewDeviceSecurityChallenge` = "settings/add_new_device/security_challenge"
  case `sharingMemberDetails` = "sharing/member/details"
  case `autofillDropdownSuggestionSearch` = "autofill/dropdown/suggestion/search"
  case `dropdownAutofillPasswordGeneratorOptions` = "dropdown/autofill/password_generator/options"
  case `tacDarkWebInsights` = "tac/dark_web_insights"
  case `tacSettingsDirectorySyncSelfHostedScim` = "tac/settings/directory_sync/self_hosted_scim"
  case `importChrome` = "import/chrome"
  case `itemCreditCard` = "item/credit_card"
  case `navigationRevampAnnouncementWelcome` = "navigation_revamp_announcement/welcome"
  case `background`
  case `loginDeviceTransferQrCode` = "login/device_transfer/qr_code"
  case `toolsPasswordChangerErrorUnknownError` = "tools/password_changer/error/unknown_error"
  case `settingsAccountChangeContactEmail` = "settings/account/change_contact_email"
  case `autofillAuthentication` = "autofill/authentication"
  case `autofillNotification` = "autofill/notification"
  case `itemWebsiteCreate` = "item/website/create"
  case `tacDashboard` = "tac/dashboard"
  case `settingsSecurityProtectWithMasterPasswordEnable` =
    "settings/security/protect_with_master_password/enable"
  case `autofillNotificationSave` = "autofill/notification/save"
  case `authenticatorAppIntroSecurelyLogin` = "authenticator_app/intro_securely_login"
  case `autofillDropdownAddCustomField` = "autofill/dropdown/add_custom_field"
  case `itemCredentialCreateOptionList` = "item/credential/create_option/list"
  case `autofillNotificationPhishingPrevention` = "autofill/notification/phishing_prevention"
  case `itemCompanyCreate` = "item/company/create"
  case `notificationNew` = "notification/new"
  case `importSelectPasswordSource` = "import/select_password_source"
  case `loginToken` = "login/token"
  case `itemDriverLicence` = "item/driver_licence"
  case `confirmItemDeletion` = "confirm_item_deletion"
  case `homePasswords` = "home/passwords"
  case `settingsSecurityTwoFactorAuthenticationDisable6DigitsCode` =
    "settings/security/two_factor_authentication/disable/6_digits_code"
  case `tacActivityBeta` = "tac/activity/beta"
  case `tacModalContactSupport` = "tac/modal_contact_support"
  case `autofillNotificationAuthenticatePasskeyUserVerificationError` =
    "autofill/notification/authenticate/passkey/user_verification/error"
  case `navigationRevampAnnouncement` = "navigation_revamp_announcement"
  case `autofillNotificationAuthenticatePasskeyUserVerificationSetupLocalUnlock` =
    "autofill/notification/authenticate/passkey/user_verification/setup_local_unlock"
  case `availablePlansIntroductoryOffersFamilyDetails` =
    "available_plans/introductory_offers/family_details"
  case `joinDashlaneTeamVerifyEmailAddress` = "join_dashlane_team/verify_email_address"
  case `modal`
  case `toolsAuthenticatorSetup` = "tools/authenticator/setup"
  case `autofillTutorialHowToSyncInformation` = "autofill/tutorial/how_to_sync_information"
  case `notificationFollowUpNotificationContent` = "notification/follow_up_notification/content"
  case `dropdownAutofillSuggestionOptions` = "dropdown/autofill/suggestion/options"
  case `loginMasterPasswordAccountRecoveryCreateNewMp` =
    "login/master_password/account_recovery_create_new_mp"
  case `toolsPasswordHealthListExcluded` = "tools/password_health/list/excluded"
  case `autofillDropdownAddIdCard` = "autofill/dropdown/add_id_card"
  case `tools`
  case `availablePlansIntroductoryOffers` = "available_plans/introductory_offers"
  case `dropdownAutofillReactivation` = "dropdown/autofill/reactivation"
  case `notificationFollowUpNotificationReminder` = "notification/follow_up_notification/reminder"
  case `settingsSecurityRecoveryKeyGenerateNew` = "settings/security/recovery_key/generate_new"
  case `passwordHistory` = "password_history"
  case `sharingList` = "sharing/list"
  case `settingsSecurityRecoveryKeyStore` = "settings/security/recovery_key/store"
  case `itemIdCard` = "item/id_card"
  case `toolsPasswordHealthListCompromised` = "tools/password_health/list/compromised"
  case `autofillDropdownAddDriverLicense` = "autofill/dropdown/add_driver_license"
  case `accountCreationPasswordTips` = "account_creation/password_tips"
  case `itemSecretDetails` = "item/secret/details"
  case `paywallPasswordLimit` = "paywall/password_limit"
  case `modalEndOfTrialReached` = "modal/end_of_trial_reached"
  case `autofillDropdownAddAddress` = "autofill/dropdown/add_address"
  case `importCsv` = "import/csv"
  case `settingsAskAutofillActivation` = "settings/ask_autofill_activation"
  case `accountCreation` = "account_creation"
  case `toolsPasswordHealthListReused` = "tools/password_health/list/reused"
  case `autofillNotificationLoginCreated` = "autofill/notification/login_created"
  case `availablePlansPremiumDetails` = "available_plans/premium_details"
  case `notificationOnboarding` = "notification/onboarding"
  case `settingsSecurityTwoFactorAuthenticationEnable` =
    "settings/security/two_factor_authentication/enable"
  case `autofillTutorial` = "autofill/tutorial"
  case `autofillNotificationOnboarding` = "autofill/notification/onboarding"
  case `installExtensionModal` = "install_extension_modal"
  case `settingsSecurityTwoFactorAuthenticationEnableBackupCodes` =
    "settings/security/two_factor_authentication/enable/backup_codes"
  case `notificationAutofill` = "notification/autofill"
  case `loginMasterPassword` = "login/master_password"
  case `dropdownAutofillPasswordGenerator` = "dropdown/autofill/password_generator"
  case `settingsAddNewDeviceTransferCancelled` = "settings/add_new_device/transfer_cancelled"
  case `freeTrialStarted` = "free_trial_started"
  case `itemFiscalStatementDetails` = "item/fiscal_statement/details"
  case `autofillNotificationOnboardingDashlanePro` = "autofill/notification/onboarding/dashlane_pro"
  case `sharingCreatePermission` = "sharing/create/permission"
  case `availablePlansFamilyDetails` = "available_plans/family_details"
  case `joinDashlaneTeam` = "join_dashlane_team"
  case `autofillNotificationAuthenticatePasskeyUserVerification` =
    "autofill/notification/authenticate/passkey/user_verification"
  case `joinDashlaneTeamExpiredInvitation` = "join_dashlane_team/expired_invitation"
  case `homeQuickActionsDropdown` = "home/quick_actions_dropdown"
  case `itemPersonalInfoList` = "item/personal_info/list"
  case `tacConfirmSubscriptionCancellationRequestSubmission` =
    "tac/confirm_subscription_cancellation_request_submission"
  case `homeIds` = "home/ids"
  case `settingsDevice` = "settings/device"
  case `itemSecretCreate` = "item/secret/create"
  case `itemIdCardCreate` = "item/id_card/create"
  case `sharingCreateMember` = "sharing/create/member"
  case `autofillExplorePasswordsSearch` = "autofill/explore_passwords/search"
  case `passwordHistorySaved` = "password_history/saved"
  case `menu`
  case `notificationHome` = "notification/home"
  case `settingsGeneral` = "settings/general"
  case `autofillAccessibilitySuggestion` = "autofill/accessibility/suggestion"
  case `paywallVpn` = "paywall/vpn"
  case `importDashEnterDashPassword` = "import/dash/enter_dash_password"
  case `itemPayment` = "item/payment"
  case `tacSettingsDirectorySyncSamlProvisioning` = "tac/settings/directory_sync/saml_provisioning"
  case `autofillNotificationAuthenticatePasskeyUserVerificationBiometric` =
    "autofill/notification/authenticate/passkey/user_verification/biometric"
  case `joinDashlaneTeamEnterEmailAddress` = "join_dashlane_team/enter_email_address"
  case `plansManagementCancelDone` = "plans_management/cancel_done"
  case `itemSecureNoteCreate` = "item/secure_note/create"
  case `itemDriverLicenceCreate` = "item/driver_licence/create"
  case `familyDashboard` = "family/dashboard"
  case `navigationRevampAnnouncementNewLook` = "navigation_revamp_announcement/new_look"
  case `settingsSecurityTwoFactorAuthenticationEnableBackupPhoneNumber` =
    "settings/security/two_factor_authentication/enable/backup_phone_number"
  case `toolsDarkWebMonitoring` = "tools/dark_web_monitoring"
  case `itemAddressCreate` = "item/address/create"
  case `toolsAuthenticatorLogins` = "tools/authenticator/logins"
  case `onboardingTrustScreens` = "onboarding/trust_screens"
  case `toolsDarkWebMonitoringList` = "tools/dark_web_monitoring/list"
  case `tacSettingsDirectorySyncActiveDirectory` = "tac/settings/directory_sync/active_directory"
  case `settingsSecurityProtectWithMasterPasswordSecureNotesEnable` =
    "settings/security/protect_with_master_password_secure_notes/enable"
  case `settingsConfirmAutofillActivation` = "settings/confirm_autofill_activation"
  case `tacSettingsPolicies` = "tac/settings/policies"
  case `autofillExplorePasswords` = "autofill/explore_passwords"
  case `itemAll` = "item/all"
  case `settingsSecurityRecoveryKeySuccess` = "settings/security/recovery_key/success"
  case `autofillNotificationFrozenAccount` = "autofill/notification/frozen_account"
  case `settings`
  case `tacModalPlansComparison` = "tac/modal_plans_comparison"
  case `settingsSecurityProtectWithMasterPasswordCredentialsDisable` =
    "settings/security/protect_with_master_password_credentials/disable"
  case `loginEmail` = "login/email"
  case `homePayments` = "home/payments"
  case `tacSettingsDirectorySyncPaywall` = "tac/settings/directory_sync/paywall"
  case `itemPassportCreate` = "item/passport/create"
  case `authenticatorAppIntroAddSecurityLayer` = "authenticator_app/intro_add_security_layer"
  case `unlockMp` = "unlock/mp"
  case `autofillDropdownAddFiscal` = "autofill/dropdown/add_fiscal"
  case `collectionCreate` = "collection/create"
  case `tacModalTrialHasBeenExtended` = "tac/modal_trial_has_been_extended"
  case `autofillNotificationOnboardingTryAgainOrGoApp` =
    "autofill/notification/onboarding/try_again_or_go_app"
  case `itemId` = "item/id"
  case `settingsSecurity` = "settings/security"
  case `settingsSecurityProtectWithMasterPasswordCredentials` =
    "settings/security/protect_with_master_password_credentials"
  case `itemCredentialList` = "item/credential/list"
  case `collectionEdit` = "collection/edit"
  case `dropdownAutofill` = "dropdown/autofill"
  case `autofillDropdownPasswordGeneratorSettings` = "autofill/dropdown/password_generator/settings"
  case `settingsAutofill` = "settings/autofill"
  case `itemBankStatement` = "item/bank_statement"
  case `loginDeviceTransferQrCodeError` = "login/device_transfer/qr_code/error"
  case `tacIntegrations` = "tac/integrations"
  case `itemPhone` = "item/phone"
  case `settingsSecurityProtectWithMasterPasswordPayments` =
    "settings/security/protect_with_master_password_payments"
  case `itemIdentityDetails` = "item/identity/details"
  case `notificationGettingStarted` = "notification/getting_started"
  case `tacSettingsSsoLegacy` = "tac/settings/sso_legacy"
  case `itemPasskeyDetails` = "item/passkey/details"
  case `importCsvDecryptLastpassVault` = "import/csv/decrypt_lastpass_vault"
  case `itemCreditCardDetails` = "item/credit_card/details"
  case `plansManagementCancelError` = "plans_management/cancel_error"
  case `loginDeviceTransferSuccess` = "login/device_transfer/success"
  case `notificationAutofillSave` = "notification/autofill/save"
  case `notificationFollowUpNotification` = "notification/follow_up_notification"
  case `settingsAddNewDeviceAttemptLimitReached` = "settings/add_new_device/attempt_limit_reached"
  case `tacSettingsSso` = "tac/settings/sso"
  case `loginDeviceTransfer2Fa` = "login/device_transfer/2fa"
  case `loginWebauthn` = "login/webauthn"
  case `itemPaymentList` = "item/payment/list"
  case `itemSecureNoteDetails` = "item/secure_note/details"
  case `sharingGroupItem` = "sharing/group/item"
  case `toolsPasswordChangerCompatibleCredentialsList` =
    "tools/password_changer/compatible_credentials_list"
  case `itemPaypalDetails` = "item/paypal/details"
  case `autofillDropdownReactivationLoginOrCreateAccount` =
    "autofill/dropdown/reactivation_login_or_create_account"
  case `autofillNotificationAuthenticatePasskeyUserVerificationPin` =
    "autofill/notification/authenticate/passkey/user_verification/pin"
  case `unlock`
  case `referral`
  case `availablePlansFreeDetails` = "available_plans/free_details"
  case `navigationRevampAnnouncementNewFilters` = "navigation_revamp_announcement/new_filters"
  case `toolsPasswordChangerCompatibleCredentialsListEmptyState` =
    "tools/password_changer/compatible_credentials_list/empty_state"
  case `itemPassport` = "item/passport"
  case `trialUpgradeSuggestion` = "trial_upgrade_suggestion"
  case `availablePlansEssentialsDetails` = "available_plans/essentials_details"
  case `plansManagement` = "plans_management"
  case `accountCreationEmail` = "account_creation/email"
  case `notificationFollowUpNotificationDiscovery` = "notification/follow_up_notification/discovery"
  case `sharingCreateItem` = "sharing/create/item"
  case `availablePlansIntroductoryOffersEssentialsDetails` =
    "available_plans/introductory_offers/essentials_details"
  case `loginDeviceTransferSetupBiometrics` = "login/device_transfer/setup_biometrics"
  case `autofillDropdownCorrect` = "autofill/dropdown/correct"
  case `homeOnboardingChecklist` = "home/onboarding_checklist"
  case `autofillDropdownAddEmail` = "autofill/dropdown/add_email"
  case `autofillExplorePasswordsCreate` = "autofill/explore_passwords/create"
  case `passwordGenerator` = "password_generator"
  case `itemSecret` = "item/secret"
  case `login`
  case `homeOnboardingChecklistAddFirstLogin` = "home/onboarding_checklist/add_first_login"
  case `settingsSecurityTwoFactorAuthenticationEnableQrCode` =
    "settings/security/two_factor_authentication/enable/qr_code"
  case `autofill`
  case `tacActivityDownload` = "tac/activity/download"
  case `autofillNotificationUpdateOrSaveAsNew` = "autofill/notification/update_or_save_as_new"
  case `itemAllList` = "item/all/list"
  case `search`
  case `adminConsolePreview` = "admin/console_preview"
  case `authenticatorAppAddAccountTokenHowToTurnOn2FaHelp` =
    "authenticator_app/add_account_token/how_to_turn_on_2fa/help"
  case `toolsPasswordHealth` = "tools/password_health"
  case `autofillNotificationAuthenticatePasskey` = "autofill/notification/authenticate/passkey"
  case `autofillNotificationAuthenticatePasskeyUserVerificationMasterPassword` =
    "autofill/notification/authenticate/passkey/user_verification/master_password"
  case `authenticatorAppAddAccountTokenHowToTurnOn2Fa` =
    "authenticator_app/add_account_token/how_to_turn_on_2fa"
  case `toolsPasswordGenerator` = "tools/password_generator"
  case `collectionList` = "collection/list"
  case `accountCreationUnlockOption` = "account_creation/unlock_option"
  case `homeOnboardingChecklistAddDevice` = "home/onboarding_checklist/add_device"
  case `autofillDropdownSuggestion` = "autofill/dropdown/suggestion"
  case `unlockPin` = "unlock/pin"
  case `homeOnboardingChecklistTryAutofillStorePersonalInfo` =
    "home/onboarding_checklist/try_autofill/store_personal_info"
  case `settingsAddNewDeviceScanQrCode` = "settings/add_new_device/scan_qr_code"
  case `autofillExplorePasswordsCreateConfirmation` =
    "autofill/explore_passwords/create/confirmation"
  case `itemIdentity` = "item/identity"
  case `itemPersonalInfo` = "item/personal_info"
  case `sharingGroup` = "sharing/group"
  case `collectionDetails` = "collection/details"
  case `toolsPasswordGeneratorHistory` = "tools/password_generator/history"
  case `authenticatorAppAddAccountTokenHowToSetupCodeHelp` =
    "authenticator_app/add_account_token/how_to_setup_code/help"
  case `settingsSecurityProtectWithMasterPasswordCredentialsEnable` =
    "settings/security/protect_with_master_password_credentials/enable"
  case `itemFiscalStatementCreate` = "item/fiscal_statement/create"
  case `loginTokenEmail` = "login/token/email"
  case `autofillNotificationSuggestion` = "autofill/notification/suggestion"
  case `tacAccountTrialEndModal` = "tac/account/trial_end_modal"
  case `autofillNotificationWarning` = "autofill/notification/warning"
  case `toolsPasswordChangerErrorNetworkFailure` = "tools/password_changer/error/network_failure"
  case `homeOnboardingChecklistTryAutofill` = "home/onboarding_checklist/try_autofill"
  case `sharingCreate` = "sharing/create"
  case `autofillNotificationAuthenticatePasskeySuccess` =
    "autofill/notification/authenticate/passkey/success"
  case `loginTokenAuthenticator` = "login/token/authenticator"
  case `notificationSharingList` = "notification/sharing/list"
  case `authenticatorAppAddAccountTokenHowToSetupCode` =
    "authenticator_app/add_account_token/how_to_setup_code"
  case `tacAccountPaymentMethod` = "tac/account/payment_method"
  case `itemAddressDetails` = "item/address/details"
  case `tacSsoPaywall` = "tac/sso/paywall"
  case `settingsDeviceList` = "settings/device/list"
  case `itemAddress` = "item/address"
  case `collection`
  case `tacAccountContactSupport` = "tac/account/contact_support"
  case `itemWebsite` = "item/website"
  case `toolsAuthenticatorWelcome` = "tools/authenticator/welcome"
  case `notificationPromotionsList` = "notification/promotions/list"
  case `plansManagementAskCancel` = "plans_management/ask_cancel"
  case `autofillTutorialHowToLogin` = "autofill/tutorial/how_to_login"
  case `joinDashlaneTeamCreateMasterPassword` = "join_dashlane_team/create_master_password"
  case `tacSettingsDirectorySync` = "tac/settings/directory_sync"
  case `itemPassportDetails` = "item/passport/details"
  case `itemIdList` = "item/id/list"
  case `settingsSecurityProtectWithMasterPasswordPaymentsEnable` =
    "settings/security/protect_with_master_password_payments/enable"
  case `sharingMember` = "sharing/member"
  case `notificationYourAccountList` = "notification/your_account/list"
  case `keyboard`
  case `availablePlansIntroductoryOffersPremiumDetails` =
    "available_plans/introductory_offers/premium_details"
  case `autofillTutorialHowToGeneratePasswords` = "autofill/tutorial/how_to_generate_passwords"
  case `rightClickMenu` = "right_click_menu"
  case `importPasswordManager` = "import/password_manager"
  case `itemSocialSecurityStatementCreate` = "item/social_security_statement/create"
  case `tacSettingsDirectorySyncScimProvisioning` = "tac/settings/directory_sync/scim_provisioning"
  case `tacAccountCustomizeInvoice` = "tac/account/customize_invoice"
  case `authenticatorAppHomeHelp` = "authenticator_app/home/help"
  case `itemSecureNoteList` = "item/secure_note/list"
  case `notificationPromotions` = "notification/promotions"
  case `rightClickMenuTutorial` = "right_click_menu/tutorial"
  case `notificationNewList` = "notification/new/list"
  case `settingsSecurityRecoveryKeyEnable` = "settings/security/recovery_key/enable"
  case `toolsAuthenticatorExplore` = "tools/authenticator/explore"
  case `autofillDropdownReactivationLoginOnly` = "autofill/dropdown/reactivation_login_only"
  case `autofillNotificationSavePasskeySuccess` = "autofill/notification/save/passkey/success"
  case `import`
  case `autofillDropdownReactivationBiometrics` = "autofill/dropdown/reactivation_biometrics"
  case `authenticatorAppAddAccountToken` = "authenticator_app/add_account_token"
  case `importLeaveProcess` = "import/leave_process"
  case `itemCredentialDetailsWebsites` = "item/credential/details/websites"
  case `autofillWarning` = "autofill/warning"
  case `joinDashlaneTeamInstallExtension` = "join_dashlane_team/install_extension"
  case `homeAdminOnboardingChecklist` = "home/admin_onboarding_checklist"
  case `importDashSuccess` = "import/dash/success"
  case `itemEmailCreate` = "item/email/create"
  case `settingsAutofillPreferences` = "settings/autofill/preferences"
  case `settingsSecurityRecoveryKeyDisable` = "settings/security/recovery_key/disable"
  case `autofillNotificationSavePasskey` = "autofill/notification/save/passkey"
  case `settingsSecurityTwoFactorAuthenticationDisableBackupCode` =
    "settings/security/two_factor_authentication/disable/backup_code"
  case `settingsAddNewDeviceSuccess` = "settings/add_new_device/success"
  case `currentPlanDwmLearnMore` = "current_plan/dwm_learn_more"
  case `availablePlans` = "available_plans"
  case `settingsSecurityProtectWithMasterPasswordIdsEnable` =
    "settings/security/protect_with_master_password_ids/enable"
  case `userProfiling` = "user_profiling"
  case `autofillDropdownAddCompany` = "autofill/dropdown/add_company"
  case `toolsPasswordChangerCompatibleCredentialsListConfirmChange` =
    "tools/password_changer/compatible_credentials_list/confirm_change"
  case `tacUser` = "tac/user"
  case `authenticatorApp` = "authenticator_app"
  case `toolsPasswordHealthList` = "tools/password_health/list"
  case `toolsPasswordChangerSuccess` = "tools/password_changer/success"
  case `settingsAddNewDeviceTimeout` = "settings/add_new_device/timeout"
  case `notificationYourAccount` = "notification/your_account"
  case `autofillDropdownSettings` = "autofill/dropdown/settings"
  case `itemPasskey` = "item/passkey"
  case `loginDeviceTransferAccountRecoveryKey` = "login/device_transfer/account_recovery_key"
  case `paywallDarkWebMonitoring` = "paywall/dark_web_monitoring"
  case `homePersonalInfo` = "home/personal_info"
  case `accountFrozenModal` = "account_frozen_modal"
  case `loginSso` = "login/sso"
  case `autofillNotificationLinkDomain` = "autofill/notification/link_domain"
  case `autofillKeyboardSuggestion` = "autofill/keyboard/suggestion"
  case `tacAccountBillingInfo` = "tac/account/billing_info"
  case `keyboardAutofill` = "keyboard/autofill"
  case `notificationAutofillDataCapture` = "notification/autofill/data_capture"
  case `paywallDeviceSyncLimit` = "paywall/device_sync_limit"
  case `toolsPasswordHealthListWeak` = "tools/password_health/list/weak"
  case `item`
  case `tacAccountContactSupportBusiness` = "tac/account/contact_support/business"
  case `passwordHistoryAll` = "password_history/all"
  case `itemEmail` = "item/email"
  case `notificationSecurity` = "notification/security"
  case `autofillNotificationB2BTrialEndReached` = "autofill/notification/b2b_trial_end_reached"
  case `unlockBiometric` = "unlock/biometric"
  case `itemIdentityCreate` = "item/identity/create"
  case `autofillAccessibility` = "autofill/accessibility"
  case `paywallDeviceSyncLimitUnlinkDevice` = "paywall/device_sync_limit/unlink_device"
  case `accountCreationCreateAccount` = "account_creation/create_account"
  case `settingsAddNewDeviceError` = "settings/add_new_device/error"
  case `paywallSharingLimit` = "paywall/sharing_limit"
  case `sharingGroupItemList` = "sharing/group/item/list"
  case `currentPlan` = "current_plan"
  case `loginMasterPasswordAccountRecoverySuccess` =
    "login/master_password/account_recovery_success"
  case `userProfilingFamiliarityWithDashlane` = "user_profiling/familiarity_with_dashlane"
  case `itemIdCardDetails` = "item/id_card/details"
  case `toolsPasswordChangerErrorIdentityVerificationFailure` =
    "tools/password_changer/error/identity_verification_failure"
  case `toolsAuthenticatorSetupTextCode` = "tools/authenticator/setup/text_code"
  case `settingsSecurityTwoFactorAuthenticationEnableSuccessConfirmation` =
    "settings/security/two_factor_authentication/enable/success_confirmation"
  case `reviewRateUsChromeWebStore` = "review/rate_us_chrome_web_store"
  case `paywallSecureNotes` = "paywall/secure_notes"
  case `autofillDropdownAddSocialSecurity` = "autofill/dropdown/add_social_security"
  case `loginDeviceTransferHelp` = "login/device_transfer/help"
  case `itemCredentialDetails` = "item/credential/details"
  case `tacUserList` = "tac/user/list"
  case `tacOnboardingChecklist` = "tac/onboarding_checklist"
  case `dropdownAutofillSuggestion` = "dropdown/autofill/suggestion"
  case `autofillNotificationDataCapture` = "autofill/notification/data_capture"
  case `homeAll` = "home/all"
  case `admin`
  case `itemCredentialCreateSelectWebsite` = "item/credential/create_select_website"
  case `loginDeviceTransferSetupBiometricsError` = "login/device_transfer/setup_biometrics/error"
  case `authenticatorAppAddAccountTokenHowToLogInAccountHelp` =
    "authenticator_app/add_account_token/how_to_log_in_account/help"
  case `itemPhoneCreate` = "item/phone/create"
  case `dropdownAutofillSuggestionOptionsCorrection` =
    "dropdown/autofill/suggestion/options/correction"
  case `itemCompanyDetails` = "item/company/details"
  case `autofillDropdownAddIdentity` = "autofill/dropdown/add_identity"
  case `autofillNotificationFreeUserPasswordLimitReached` =
    "autofill/notification/free_user_password_limit_reached"
  case `itemCredentialCreateOption` = "item/credential/create_option"
  case `settingsSecurityProtectWithMasterPasswordSecureNotes` =
    "settings/security/protect_with_master_password_secure_notes"
  case `autofillDropdownAddPassword` = "autofill/dropdown/add_password"
  case `settingsSecurityChangeMasterPassword` = "settings/security/change_master_password"
  case `settingsSecurityProtectWithMasterPasswordDisable` =
    "settings/security/protect_with_master_password/disable"
  case `joinDashlaneTeamPendingInvitation` = "join_dashlane_team/pending_invitation"
  case `tacSubmitAnOrder` = "tac/submit_an_order"
  case `itemCreditCardCreate` = "item/credit_card/create"
  case `importCsvLoginToLastpass` = "import/csv/login_to_lastpass"
  case `settingsThiswebsite` = "settings/thiswebsite"
  case `toolsPasswordChangerCredential` = "tools/password_changer/credential"
  case `paywall`
  case `tacGroup` = "tac/group"
  case `autofillDropdown` = "autofill/dropdown"
  case `importDash` = "import/dash"
  case `paywallFrozenAccount` = "paywall/frozen_account"
  case `toolsPasswordChangerCredentialConfirmChange` =
    "tools/password_changer/credential/confirm_change"
  case `autofillDropdownPasswordGenerator` = "autofill/dropdown/password_generator"
  case `family`
  case `settingsSecurityProtectWithMasterPasswordIdsDisable` =
    "settings/security/protect_with_master_password_ids/disable"
  case `itemDriverLicenceDetails` = "item/driver_licence/details"
  case `accountCreationCreateMasterPassword` = "account_creation/create_master_password"
  case `itemCredential` = "item/credential"
  case `tacModalReasonsToExtendTrial` = "tac/modal_reasons_to_extend_trial"
  case `itemBankStatementCreate` = "item/bank_statement/create"
  case `home`
  case `loginMasterPasswordAccountRecoveryEnterRecoveryKey` =
    "login/master_password/account_recovery_enter_recovery_key"
  case `notificationSecurityDetails` = "notification/security/details"
  case `sharing`
  case `settingsSecurityRecoveryKey` = "settings/security/recovery_key"
  case `tacIntegrationsSplunk` = "tac/integrations/splunk"
  case `itemPhoneDetails` = "item/phone/details"
  case `tacGroupList` = "tac/group/list"
  case `loginDeviceTransferSecurityChallenge` = "login/device_transfer/security_challenge"
  case `paywallFreeUserPasswordLimitReached` = "paywall/free_user_password_limit_reached"
  case `keyboardAutofillSuggestion` = "keyboard/autofill/suggestion"
  case `autofillNotificationOnboardingFirstPasswordSaved` =
    "autofill/notification/onboarding/first_password_saved"
  case `loginDeviceTransferSetPin` = "login/device_transfer/set_pin"
  case `settingsSecurityRecoveryKeyConfirm` = "settings/security/recovery_key/confirm"
  case `toolsPasswordHealthOverview` = "tools/password_health/overview"
  case `autofillDropdownAddPhone` = "autofill/dropdown/add_phone"
  case `toolsVpnPrivacyConsent` = "tools/vpn/privacy_consent"
  case `tacActivityList` = "tac/activity/list"
  case `authenticatorAppIntroBackupWithPwm` = "authenticator_app/intro_backup_with_pwm"
  case `loginDeviceTransfer` = "login/device_transfer"
  case `notificationSharing` = "notification/sharing"
  case `privacySettings` = "privacy_settings"
  case `autofillDropdownAddCreditCard` = "autofill/dropdown/add_credit_card"
  case `toolsNewDevice` = "tools/new_device"
  case `toolsPasswordChanger` = "tools/password_changer"
  case `tacSettingsAccountRecovery` = "tac/settings/account_recovery"
  case `itemSocialSecurityStatementDetails` = "item/social_security_statement/details"
  case `homeAddItemDropdown` = "home/add_item_dropdown"
  case `settingsPlanPage` = "settings/plan_page"
  case `itemCredentialCreate` = "item/credential/create"
  case `itemSecureNote` = "item/secure_note"
  case `notificationAutofillReplace` = "notification/autofill/replace"
  case `toolsAuthenticator` = "tools/authenticator"
  case `notification`
  case `notificationGettingStartedList` = "notification/getting_started/list"
  case `tacAccountContactSupportTeam` = "tac/account/contact_support/team"
  case `authenticatorAppAddAccountTokenSelectSetupMethod` =
    "authenticator_app/add_account_token/select_setup_method"
  case `settingsSecurityProtectWithMasterPasswordSecureNotesDisable` =
    "settings/security/protect_with_master_password_secure_notes/disable"
  case `tacModalTrialExpiresToday` = "tac/modal_trial_expires_today"
  case `homeSecureNotes` = "home/secure_notes"
  case `autofillNotificationRememberAlert` = "autofill/notification/remember_alert"
  case `paywallFamily` = "paywall/family"
  case `autofillNotificationAutofillIsDisabled` = "autofill/notification/autofill_is_disabled"
  case `tacAccount` = "tac/account"
  case `paywallB2B` = "paywall/b2b"
  case `tacSettingsDirectorySyncConfidentialScim` = "tac/settings/directory_sync/confidential_scim"
  case `toolsMore` = "tools/more"
  case `toolsVpn` = "tools/vpn"
  case `autofillNotificationLoginUpdated` = "autofill/notification/login_updated"
  public var isPriority: Bool {
    switch self {
    case .loginTokenEmail, .accountCreationEmail, .loginToken, .accountCreationTermsServices,
      .onboardingTrustScreens, .loginEmail, .loginTokenAuthenticator, .toolsNewDevice,
      .accountCreationCreateMasterPassword, .unlockMp, .accountCreationCreateAccount, .unlockPin,
      .unlockBiometric, .onboarding:
      return true
    default: return false
    }
  }
}
